[project]
name = "gatekeepr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentops>=0.4.10",
    "chainlit>=2.5.5",
    "openai-agents[viz]>=0.0.14",
    "rich>=14.0.0",
]
